
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/colegio?autoReconnect=true&useSSL=false
    username: root
    password: 
    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

    
server:
  port: 8085


