
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usersdb?autoReconnect=true&useSSL=false
    username: victor
    password:
    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

    
server:
  port: 9095


